private: false
name: INLG 2025
tagline: INLG 2025
date: October 29 - November 2, 2025
place: Hanoi, Vietnam
citation_date: TBA
proceedings_title: Proceedings of the 18th International Natural Language Generation Conference
analytics: UA-
logo:
  image: static/images/inlg_logo.png
# uncomment the following line to show the site title next to the logo image
site_title:
page_title:
  prefix: "INLG 2025"
  separator: ": "
background_image: static/images/viasm_banner.jpg
organization: INLG 2025 Organizers

calendar:
  colors: #  Colors for the different event hashtags:
    ---: "#bed972"
    qa: "#4FCAEB"
    talk: "#ccc"
  sunday_saturday: false #  Include Sunday and Saturday
